---
name: concourse

# replace with `bosh status --uuid`
# TODO - Look into using Bosh2 and thus the "env" command
director_uuid: REPLACE_WITH_DIRECTOR_ID

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest
- name: postgres
  version: latest

stemcells:
- alias: trusty
  name: bosh-azure-hyperv-ubuntu-trusty-go_agent
  version: latest

instance_groups:
- name: web
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: concourse_web_or_db
  stemcell: trusty
  azs: [z1]
  networks: [{name: concourse, default: [dns, gateway]}, {name: public, static_ips: [REPLACE_WITH_CONCOURSE_PUBLIC_IP]}]
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: http://REPLACE_WITH_CONCOURSE_PUBLIC_IP:8080

      # replace with username/password, or configure GitHub auth
      basic_auth_username: REPLACE_WITH_CONCOURSE_USERNAME
      basic_auth_password: REPLACE_WITH_CONCOURSE_PASSWORD

      # NEW for Concourse 3.x - need the signing key
      token_signing_key: ((token_signing_key))

      postgresql:
        database: &db_name atc
        role: &db_role
          name: concourse
          password: REPLACE_WITH_CONCOURSE_DB_ROLE_PASSWORD

  - name: tsa
    release: concourse
    properties: 
      log_level: debug
      host_key: ((tsa_host_key))
      token_signing_key: ((token_signing_key))
      authorized_keys: [((worker_key.public_key))]

- name: db
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: concourse_web_or_db
  stemcell: trusty
  # replace with a disk type from your BOSH Director's cloud config
  persistent_disk_type: default
  azs: [z1]
  networks: [{name: concourse}]
  jobs:
  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: *db_name
        roles:
        - *db_role

- name: worker
  # Adjust this how you see fit
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: concourse_worker
  stemcell: trusty
  azs: [z1]
  networks: [{name: concourse}]
  jobs:
  - release: concourse
    name: worker
    consumes: {baggageclaim: {from: worker-baggageclaim}}
    properties:
      drain_timeout: 10m
      tsa: {worker_key: ((worker_key))}
  - name: baggageclaim
    release: concourse
    properties: {log_level: debug}
  - name: garden
    release: garden-runc
    properties:
      garden:
        graph_cleanup_threshold_in_mb: REPLACE_WITH_CONCOURSE_GRAPH_CLEANUP_THRESHOLD
        listen_network: tcp
        listen_address: 0.0.0.0:7777
variables:
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
